version: 2


steps: &steps
  steps:
    - restore_cache:
        keys:
          - cache-{{ .Environment.CIRCLE_JOB }}
    - checkout
    - run:
        name: Build package dependencies
        command: python3 -m pip install --user pandas scipy antspyx antspynet tensorflow
    - run:
        name: Build package
        command: python3 -m pip install .
    - run:
        name: Check package
        command: python3 tests/test_reference_run.py

